services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "${DJANGO_PORT}:8000"
    command: python manage.py runserver 0.0.0.0:${DJANGO_PORT}
    env_file:
      - ../.env
    volumes:
      - ..:/app
    depends_on:
      - postgres  # Посилання на базу даних
